map_update_interval: 2.0
maxUrange: 5.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 50
srr: 0.001
srt: 0.002
str: 0.001
stt: 0.002
linearUpdate: 0.5
angularUpdate: 0.4
temporalUpdate: 2.0
resampleThreshold: 0.5
particles: 30
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
maxRange: 5.5
transform_publish_period: 0.05

